[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "os_script"
# change in the "os_script/os_script.py" file: `def os_script_version():`
# and run "build_and_install.py"
version = "0.5.5"
requires-python = ">=3.3"
description = "Library for shell scripting in Python"
authors = [{name = "heX", email = "hex1625616@gmail.com"}]
license = "MIT"
license-files = ["LICENSE.txt"]
readme = "README.md"
keywords = ["shell", "scripting", "system", "files", "processes", "utils"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "psutil>=5.5.0"
]

[project.urls]
Homepage = "https://github.com/heX16/os-script"
Repository = "https://github.com/heX16/os-script"
Issues = "https://github.com/heX16/os-script/issues"

[project.optional-dependencies]
dev = [
  "pytest>=6.0",
  "black",
  "isort"
]

[tool.setuptools.packages.find]
include = ["os_script*"]
exclude = ["todo*", "tests*", "examples*", "_other*"]

[tool.black]
line-length = 88
target-version = ['py36']
